on:
  workflow_dispatch:
  # schedule:
  # - cron: '0 */4 * * *'

permissions:
  contents: read

jobs:
  prune_stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    name: Prune Stale
    runs-on: ubuntu-22.04
    # do not run it in forked repos
    if: github.repository == 'uptrace/bun'

    steps:
    - name: Prune Stale
      uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e  # v9.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Different amounts of days for issues/PRs are not currently supported but there is a PR
        # open for it: https://github.com/actions/stale/issues/214
        days-before-stale: 30
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had activity in the
          last 30 days.
          If there is no update within the next 7 days, this issue will be closed.
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not had
          activity in the last 30 days.
          If there is no update within the next 7 days, this pr will be closed.
          Please feel free to give a status update now, ping for review, when it's ready.
          Thank you for your contributions!
        stale-issue-label: 'stale'
        exempt-issue-labels: 'no stalebot,help wanted'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'no stalebot'
        operations-per-run: 500
        ascending: true
        debug-only: true
